### ISSUE TITLE
where is castor_windy?

### ISSUE THREAD

**Issue by spider623** [sonyxperiadev/device-sony-castor#10]
I want to build 5.1 from source but I can't find any entries for SPG511, why? Is the source for the castor and castor_windy unified?  If not why Sony doesn't give us the binaries, what are difference between the two code wise?

**Comment by jerpelea** [comment]
The only difference is kernel blob and telephony stack
Blobs are the same

**Comment by spider623** [comment]
so i can basically build it and flash the kernel from the stock sony image with no issues?

**Comment by jerpelea** [comment]
you should compile kernel binary yourself and replace provided kernel

**Comment by spider623** [comment]
thanks, will do once i find time
